# ここでバージョンを指定
version: 2

# 実行に関する設定
run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  # スクリプトディレクトリを除外
  skip-dirs:
    - scripts

# 有効にするlinter
linters:
  enable:
    - cyclop
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gochecknoglobals
    - gocritic
    - goconst
    - gocyclo
    - err113
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - revive
    - unconvert
    - unparam
    - whitespace

# linterの設定
linters-settings:
  funlen:
    lines: 100
    statements: 50
  mnd:
    # デフォルトで許可する値のリスト
    allowed-numbers:
      - 0
      - 1
      - 2
      - 100 # 100%など
    # デフォルトの除外設定
    ignored-numbers:
      - "0666" # ファイルパーミッション
      - "0755" # ディレクトリパーミッション
      - "0644" # 一般的なファイルパーミッション
    # チェックしない関数
    ignored-functions:
      - time.Date
      - time.Sleep

# 問題検出の設定
issues:
  # テストファイルに対する特定のlinterを除外
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
        - gosec
        - funlen
        - noctx