version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - "^scripts/"
      - ".*_test\\.go$"

# Linter 全体設定
linters:
  enable:
    - cyclop
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gochecknoglobals
    - gocritic
    - goconst
    - gocyclo
    - err113
    - mnd
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - revive
    - unconvert
    - unparam
    - whitespace
    - errcheck

  exclusions:
    paths:
      - "^scripts/"
      - ".*_test\\.go$"

  settings:
    funlen:
      lines: 100
      statements: 50
    mnd:
      ignored-numbers:
        - "0666"
        - "0755"
        - "0644"
      ignored-functions:
        - time.Date
        - time.Sleep
