name: Galick CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: true
        default: 'dev'
      scenario:
        description: 'Scenario to run'
        required: true
        default: 'simple'
      threshold_failure:
        description: 'Fail workflow on threshold violations'
        required: true
        default: true
        type: boolean

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.extract.outputs.go-version }}
      vegeta-version: ${{ steps.extract.outputs.vegeta-version }}
      golangci-lint-version: ${{ steps.extract.outputs.golangci-lint-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract versions from Makefile
        id: extract
        run: |
          echo "go-version=$(grep "GO_VERSION=" Makefile | cut -d= -f2)" >> $GITHUB_OUTPUT
          echo "vegeta-version=$(grep "VEGETA_VERSION=" Makefile | cut -d= -f2)" >> $GITHUB_OUTPUT
          echo "golangci-lint-version=$(grep "GOLANGCI_LINT_VERSION=" Makefile | cut -d= -f2)" >> $GITHUB_OUTPUT

  lint-and-test:
    name: Lint and Test
    needs: get-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.get-versions.outputs.go-version }}
          cache: true

      - name: Install golangci-lint manually
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ needs.get-versions.outputs.golangci-lint-version }}
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
  load-test:
    name: Load Test
    needs: [get-versions, lint-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker Tags
        id: docker-tag-loadtest
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "GALICK_TAG=galick:pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "DEMO_TAG=demo-server:pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "GALICK_TAG=galick:latest" >> $GITHUB_OUTPUT
            echo "DEMO_TAG=demo-server:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build Galick Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.docker-tag-loadtest.outputs.GALICK_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Demo Server Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.demo
          push: false
          load: true
          tags: ${{ steps.docker-tag-loadtest.outputs.DEMO_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Docker Images
        run: |
          docker images
          docker run --rm ${{ steps.docker-tag-loadtest.outputs.GALICK_TAG }} version

      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
          find . -name "*.sh" -exec chmod +x {} \;
          # Verify scripts are executable
          ls -la scripts/pre-load.sh
          ls -la scripts/post-load.sh

      - name: Start Demo Server
        run: |
          docker run -d --name demo-server -p 8080:8080 ${{ steps.docker-tag-loadtest.outputs.DEMO_TAG }}
          sleep 5  # Wait for server to start
          # Verify the server is running
          curl -s http://localhost:8080/api/health || echo "Warning: Server health check failed"

      - name: Run Load Tests (Manual Trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p output
          # Add demo-server to hosts file to make it resolve to localhost
          echo "127.0.0.1 demo-server" | sudo tee -a /etc/hosts
          # Run load tests with base_url via environment variable
          docker run --network host -v $(pwd)/output:/data/output -v $(pwd)/loadtest.yaml:/data/loadtest.yaml \
            -e CI=${{ inputs.threshold_failure }} \
            -e BASE_URL=http://localhost:8080 \
            ${{ steps.docker-tag-loadtest.outputs.GALICK_TAG }} run ${{ inputs.scenario }} --env ${{ inputs.environment }} --config /data/loadtest.yaml

      - name: Run Load Tests (Automated)
        if: github.event_name != 'workflow_dispatch'
        run: |
          mkdir -p output
          # Add demo-server to hosts file to make it resolve to localhost
          echo "127.0.0.1 demo-server" | sudo tee -a /etc/hosts
          # Run load tests with base_url via environment variable
          docker run --network host -v $(pwd)/output:/data/output -v $(pwd)/loadtest.yaml:/data/loadtest.yaml \
            -e CI=true \
            -e BASE_URL=http://localhost:8080 \
            ${{ steps.docker-tag-loadtest.outputs.GALICK_TAG }} run --config /data/loadtest.yaml

      - name: Generate HTML Report
        run: |
          docker run --network host -v $(pwd)/output:/data/output -v $(pwd)/loadtest.yaml:/data/loadtest.yaml ${{ steps.docker-tag-loadtest.outputs.GALICK_TAG }} report --format html

      - name: Stop Demo Server
        run: |
          docker stop demo-server || true
          docker rm demo-server || true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: load-test-reports
          path: output/

      - name: Check for Threshold Violations
        run: |
          if grep -q "❌ FAILED" output/*/*/report.md; then
            echo "::warning::Threshold violations detected in load test results"
            if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.threshold_failure }}" == "true" ]] || [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
              echo "::error::Load test thresholds violated"
              exit 1
            fi
          else
            echo "All thresholds passed! 🎉"
          fi
